# Checkov Configuration for AKS Infrastructure
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Framework to scan
framework:
  - terraform

# Directory to scan
directory:
  - .

# Skip specific checks that don't apply to our architecture
skip-check:
  # We use Azure AD authentication, not local accounts
  - CKV_AZURE_141  # Ensure AKS local admin account is disabled (we use Azure AD)
  
  # Networking - we're using a dev setup with public endpoints
  - CKV_AZURE_4    # Ensure AKS cluster is private (dev environment uses public)
  - CKV_AZURE_115  # Ensure API server authorized IP ranges are configured
  
  # Cost optimization - dev environment uses Basic SKU
  - CKV_AZURE_166  # Ensure container registry uses Premium SKU
  - CKV_AZURE_165  # Ensure geo-replicated container registry
  
  # These are handled at infrastructure level or not applicable
  - CKV_AZURE_117  # Ensure AKS cluster uses disk encryption set
  - CKV_AZURE_226  # Ensure AKS cluster is not using default namespace
  - CKV_AZURE_232  # Ensure AKS cluster uses managed identity
  
  # GitOps configuration is optional in dev
  - CKV_AZURE_168  # Ensure AKS cluster has Flux extension installed

# Soft fail - don't block on warnings
soft-fail: true

# Compact output
compact: true

# Output format
output:
  - cli
  - sarif
